<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="addons\**" />
    <Compile Remove="Prefab\**" />
    <EmbeddedResource Remove="addons\**" />
    <EmbeddedResource Remove="Prefab\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="addons\cat_snapicon\Plugin_scripts\CatSnapIconPlugin.cs" />
    <Compile Include="addons\cat_snapicon\Plugin_scripts\SnapWindowComp.cs" />
    <Compile Include="addons\cat_snapicon\Plugin_scripts\UiFloatFieldView.cs" />
    <Compile Include="addons\cat_snapicon\Plugin_scripts\UiVector3View.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="addons\cat_snapicon\LICENSE.txt" />
    <Content Include="LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <None Include="addons\cat_snapicon\plugin.cfg" />
    <None Include="addons\cat_snapicon\Plugin_scenes\snap_window.tscn" />
    <None Include="addons\cat_snapicon\Plugin_scenes\UiFloatField.tscn" />
    <None Include="addons\cat_snapicon\Plugin_scenes\ui_Vector3.tscn" />
    <None Include="addons\cat_snapicon\Plugin_scripts\CatSnapIconPlugin.cs.uid" />
    <None Include="addons\cat_snapicon\Plugin_scripts\SnapWindowComp.cs.uid" />
    <None Include="addons\cat_snapicon\Plugin_scripts\UiFloatFieldView.cs.uid" />
    <None Include="addons\cat_snapicon\Plugin_scripts\UiVector3View.cs.uid" />
    <None Include="addons\cat_snapicon\README.md" />
    <None Include="addons\cat_snapicon\Theme.tres" />
    <None Include="README.md" />
    <None Include="优先级.md" />
    <None Include="开发计划.md" />
    <None Include="日志信息.md" />
  </ItemGroup>
</Project>